/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AboutView: typeof import('./src/views/AboutView.vue')['default']
    Aside: typeof import('./src/layout/Aside.vue')['default']
    Container: typeof import('./src/views/demo/Container.vue')['default']
    DynamicIcon: typeof import('./src/components/icons/DynamicIcon.vue')['default']
    ElAside: typeof import('element-plus/es')['ElAside']
    ElAvatar: typeof import('element-plus/es')['ElAvatar']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElDivider: typeof import('element-plus/es')['ElDivider']
    ElDrawer: typeof import('element-plus/es')['ElDrawer']
    ElFooter: typeof import('element-plus/es')['ElFooter']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElHeader: typeof import('element-plus/es')['ElHeader']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElImage: typeof import('element-plus/es')['ElImage']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElMain: typeof import('element-plus/es')['ElMain']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElSubMenu: typeof import('element-plus/es')['ElSubMenu']
    ElTooltip: typeof import('element-plus/es')['ElTooltip']
    Hanbeger: typeof import('./src/components/Hanbeger.vue')['default']
    Header: typeof import('./src/layout/Header.vue')['default']
    HomeView: typeof import('./src/views/HomeView.vue')['default']
    Layout: typeof import('./src/layout/Layout.vue')['default']
    LayoutDemo: typeof import('./src/views/demo/LayoutDemo.vue')['default']
    Menu: typeof import('./src/components/menu/Menu.vue')['default']
    MenuItem: typeof import('./src/components/menu/MenuItem.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SubMenu: typeof import('./src/components/menu/SubMenu.vue')['default']
    UseBreakpoints: typeof import('./src/views/demo/UseBreakpoints.vue')['default']
  }
}
